# This stage builds a dist tarball from the source
FROM ubuntu:xenial

MAINTAINER Suwat Saisema <suwat.saisema@gmail.com>
# Install dependencies
RUN apt-get update && apt-get install -yq --no-install-recommends \
    autoconf \
    automake \
    bison \
    cmake \
    flex \
    gcc \
    git \
    install-info \
    make \
    libc-ares-dev \
    libjson-c-dev \
    libpam0g-dev \
    libcap-dev \
    libpython-dev \
    libreadline-dev \
    libsystemd-dev \
    libtool \
    libsystemd-dev \
    libpcre3-dev \
    pkg-config \
    python3-dev \
    python3-pytest \
    vim \
&& rm -rf /var/lib/apt/lists/* \
# libyang
&& export GIT_SSL_NO_VERIFY=true \
&& cd /usr/local/src \
&& git clone https://github.com/CESNET/libyang.git \
&& cd libyang \
&& mkdir build \
&& cd build \
&& cmake -DENABLE_LYD_PRIV=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr \
    -D CMAKE_BUILD_TYPE:String="Release" .. \
&& make \
&& make install \
&& rm -rf /usr/local/src/libyang \
&& groupadd -r -g 92 frr \
&& groupadd -r -g 85 frrvty \
&& adduser \
    --system \
    --ingroup frr \
    --home /var/run/frr/ \
    --gecos "FRR suite" \
    --shell /sbin/nologin frr \
&& usermod -a -G frrvty frr \
# Clone Git
&& cd /usr/local/src \
&& git clone -b frr-7.3 https://github.com/frrouting/frr.git frr \
&& cd frr \
&& ./bootstrap.sh \
&& ./configure \
    --prefix=/usr \
    --includedir=\${prefix}/include \
    --enable-exampledir=\${prefix}/share/doc/frr/examples \
    --sbindir=\${prefix}/lib/frr \
    --libdir=\${prefix}/lib/frr \
    --libexecdir=\${prefix}/lib/frr \
    --localstatedir=/var/run/frr \
    --sysconfdir=/etc/frr \
    --enable-vtysh \
    --enable-isisd \
    --enable-pimd \
    --enable-watchfrr \
    --enable-ospfclient=yes \
    --enable-ospfapi=yes \
    --enable-configfile-mask=0640 \
    --enable-logfile-mask=0640 \
    --enable-rtadv \
    --enable-fpm \
    --enable-ldpd \
    --enable-systemd \
    --enable-multipath=64 \
    --enable-user=frr \
    --enable-group=frr \
    --enable-vty-group=frrvty \
    --disable-doc \
    --with-moduledir=/usr/lib/frr/modules \
    --with-libyang-pluginsdir=/usr/lib/frr/libyang_plugins \
&& make && make install \
&& install -m 775 -o frr -g frr -d /var/log/frr \
&& install -m 775 -o frr -g frrvty -d /etc/frr \
&& install -m 640 -o frr -g frrvty tools/etc/frr/vtysh.conf /etc/frr/vtysh.conf \
&& install -m 640 -o frr -g frr tools/etc/frr/frr.conf /etc/frr/frr.conf \
&& install -m 640 -o frr -g frr tools/etc/frr/daemons.conf /etc/frr/daemons.conf \
&& install -m 640 -o frr -g frr tools/etc/frr/daemons /etc/frr/daemons \
&& install -m 775 tools/frr /etc/init.d \
&& rm -rf /usr/local/src/frr

ADD docker-start /usr/sbin/docker-start
RUN chmod +x /usr/sbin/docker-start
ENTRYPOINT ["/usr/sbin/docker-start"]
